---
- name: Get firewall rules by name
  ansible.windows.win_shell: Get-NetFirewallRule -DisplayName "{{ item.display_name }}"
  register: firewall_rule_results
  with_items: "{{ firewall_to_update }}"

- name: Parse enabled firewall rules
  ansible.builtin.set_fact:
    enabled_firewall_rules: >-
      {{
        firewall_rule_results.results 
        | map(attribute='stdout_lines') 
        | select('match', '^.*Enabled\s+:\s+True.*$') 
        | list
      }}

- name: Display enabled firewall rules
  ansible.builtin.debug:
    msg: "{{ enabled_firewall_rules[0] }}"
  tags:
    - debug

- name: Copy enabled_firewall_rules to input_data
  ansible.builtin.set_fact:
    input_data: "{{ enabled_firewall_rules[0] }}"

- name: Display input_data
  ansible.builtin.debug:
    var:  input_data
  tags:
    - debug

- name: Ensure the file is deleted
  ansible.builtin.file:
    path: "{{ role_path  }}/files/transformed_data.json"
    state: absent
  delegate_to: localhost

- name: Execute the Python script
  ansible.builtin.command:  python3 {{ role_path  }}/files/string_to_dict.py "{{ input_data }}"
  delegate_to: localhost
  register: script_output
  when: input_data | length != 0

- name: Display script output
  ansible.builtin.debug:
    var:  script_output
  tags:
    - debug