---
- name: Copy file to linux host
  ansible.builtin.copy:
    src: "{{ role_path  }}/files/{{ file_name }}"
    dest: "{{ path }}/{{ file_name }}"
  register: output

- name: Display copy file output
  ansible.builtin.debug:
    var: output
  tags:
    - debug