---
- name: Ensure folder is created
  ansible.builtin.file:
    path: "{{ path }}"
    state: directory
    mode: '0700'
    group: "{{ ansible_user }}"
    owner: "{{ ansible_user }}"
  register: output

- name: Display creation folder output
  ansible.builtin.debug:
    var: output
  delegate_to: localhost
  tags:
    - debug
