---
- name: Exectute python script
  ansible.builtin.shell: python3 {{ path }}/{{ script_name }}
  args:
    executable: /bin/bash
  register: output

- name: Display script execution output
  ansible.builtin.debug:
    var: output
  delegate_to: localhost
  tags:
    - debug