---
- name: Ensure we wait long enough for the updates to be applied during reboot
  ansible.windows.win_updates:
    category_names: '*'
    reboot: true
    reboot_timeout: 3600
  register: result

- name: Show log
  ansible.builtin.debug:
    var: result
