system_os_type: windows

Ansible_pwd: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          33643030643264333539386665386439313866326638656266393765316639336562306339383464
          6331303866356639346432366466336532383763346566330a333864616634303231383235313532
          62373438613233393833386264303233393462646332353861666230303335313633373531383136
          6239656638363534630a343165313230346135353930616361633962363066373636636436343366
          3334

ansible_host: 192.168.1.165
ansible_user: Ansible
ansible_password: "{{ Ansible_pwd }}"

firewall_to_block:
  - Skype
  - Docker Desktop Backend
  - solarsystem.exe
  - Steam
  - Steam Web Helper
  - influxd
  - utorrent
  - utorrent.exe
  - Wallpaper Engine
  - squeamish.exe
  - Xbox Game UI
  - Examen
  - Xbox Game Bar Plugin
  - Xbox TCUI
  - Xbox Identity Provider
  - Game Bar
  - Calculatrice Windows
  - client.exe
  - rebextinysftpserver.exe
  - java.exe
  - nginx.exe
  - ss_project.exe
  - stremio-runtime.exe

firewall_not_to_delete:
  - Xbox Game UI
  - Xbox Game Bar Plugin
  - Xbox TCUI
  - Xbox Identity Provider
  - Game Bar
  - Calculatrice Windows

path_to_firewall_rule_bck: C:\Users\{{ ansible_user }}\firewall_workspace

firewall_rules_backup_file_name: backup.wfw

python_version: "3.12.8"

python_uri_exe: "https://www.python.org/ftp/python/{{ python_version }}/python-{{ python_version }}-amd64.exe"

ansible_python_interpreter: "python{{ python_version }}"