---
- name: Display ansible connexion user
  hosts: "{{ hostname }}"
  gather_facts: false
  vars:
    given_vault: NONE
  tasks:

    - name: Task to set given user
      ansible.builtin.set_fact:
        given_vault: "{{ ansible_user }}"
      delegate_to: localhost

    - name: Role to output user
      include_role:
        name: "common"
        tasks_from: decrypt-vault.yml
