---
- name: Display ansible connexion password
  hosts: "{{ hostname }}"
  gather_facts: false
  vars:
    given_pwd: NONE
  tasks:

    - name: Task to set given password
      ansible.builtin.set_fact:
        given_pwd: "{{ ansible_password }}"
      delegate_to: localhost

    - name: Role to output password
      include_role:
        name: "common"
        tasks_from: decrypt-password.yml
