- name: Check raspberry pie host
  hosts: raspberry
  gather_facts: false
  tasks:
    - name: Role to ping host
      include_role:
        name: "{{ system_os_type }}/ping_host"

- name: Check win10 host
  hosts: win10
  gather_facts: false
  tasks:
    - name: Role to ping host
      include_role:
        name: "{{ system_os_type }}/ping_host"