- name: Update raspberry-pie/ubuntu host
  hosts: linux
  gather_facts: false
  tasks:
    - name: Role to update
      include_role:
        name: "{{ system_os_type }}/update"

- name: Update win10 host
  hosts: win10
  gather_facts: false
  tasks:
    - name: Role to update
      include_role:
        name: "{{ system_os_type }}/update"