- name: Update raspberry pie host
  hosts: raspberry
  gather_facts: false
  tasks:
    - name: Role to get update
      include_role:
        name: "{{ system_os_type }}/update"
        tasks_from: get-update

    - name: Role to apply update
      include_role:
        name: "{{ system_os_type }}/update"
        tasks_from: upgrade-package

    - name: Role to apply update
      include_role:
        name: "{{ system_os_type }}/update"
        tasks_from: reboot-if-needed


- name: Update win10 host
  hosts: win10
  gather_facts: false
  tasks:
    - name: Role to update windows
      include_role:
        name: "{{ system_os_type }}/update"